export const FETCH_STATIONS = 'FETCH_STATIONS';
export const ON_STATIONS_LOADED = 'ON_STATIONS_LOADED';
export const ON_STATIONS_LOAD_FAIL = 'ON_STATIONS_LOAD_FAIL';
export const SELECT_STATION = 'SELECT_STATION';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const ADD_TAG_FILTER = 'ADD_TAG_FILTER';
export const REMOVE_TAG_FILTER = 'REMOVE_TAG_FILTER';